# Playground:
# https://github.com/ciscorucinski/public_repo/issues/1

name: Analyze Comments

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read

jobs:
  analyze_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ciscorucinski/private_repo      # Private Repo location
          token: ${{ secrets.PAT }}
          sparse-checkout: |                          # New-line deliminated file
            triggers.txt

      - name: Get trigger phrases from private repository
        id: get_trigger_phrases
        run: |                                         # Allows for multiline output
          {
            echo 'triggers<<EOF'
            cat triggers.txt
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Check for triggers in comment
        id: check_comment
        uses: actions/github-script@v7
        with:
          script: | 
            const comment = context.payload.comment.body;
            const triggers = `${process.env.TRIGGER_PHRASES}`.split('\n');
            return triggers.some(trigger => comment.includes(trigger));
        env:
          TRIGGER_PHRASES: ${{ steps.get_trigger_phrases.outputs.triggers }}

      - name: Delete comment if it contains any trigger
        if: steps.check_comment.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const commentId = context.payload.comment.id;
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId
            });

      # - name: Block user if comment contains any trigger
      #   if: steps.check_comment.outputs.result == 'true'
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const userId = context.payload.comment.user.id;
      #       await github.rest.users.block({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         user_id: userId
      #       });
